{
    'name': 'Store Purchase Request',
    'version': '17.0',
    'summary': 'Manage store and purchase requests',
    'description': 'A module to handle store and purchase requests in Odoo',
    'author': 'Yoraki (Yeab A).',
    'depends': ['base', 'product','stock','purchase', 'hr', 'web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        
        'data/data.xml',
        'data/equipment_issue_cron.xml',
        'views/store_request.xml',
        'views/equipment_request.xml',
        'views/equipment_issue.xml',
        'views/store_request_menu.xml',
        'views/purchase_order.xml',
        'views/store_issue.xml',
        'views/purchase_tender.xml',
        'views/vendor_tender_summary_views.xml',
        #'views/stock_picking.xml',
        'views/stock_picking_report.xml',
        'views/purchase_threshold_config_views.xml',
        'views/store_request_wizard.xml',
        "views/print/siv_template.xml",
        "views/report.xml",
        "views/po_extention.xml",
        "views/store_request_dashboard.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'store_request/static/src/js/dashboard.js',
            'store_request/static/src/xml/dashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
}
