from . import defect_wastage
from . import physical_testing_parameters
from . import  calibration_plan
from . import raw_material_inspection
from . import non_conforming_product
from . import weight_notification
from . import qc_report
from . import customer_complaint
from . import pipe_dimension
from . import parameter