{
    "name": "Vehicle Trip",
    "version": "1.0",
    "depends": ["base","fleet","stock","product","hr"],
    "author": "silesh",
    "category": "Transport",
    "description": "Vehicle Trip Management",
    "data": [
        "security/ir.model.access.csv",
        "views/vehicle_trip_views.xml",
        "views/vehicle_trip_passout_view.xml",
        "views/fuel_report_views.xml",
        # "report/report_action.xml",
        "report/passout_print_action.xml",
        # "report/vehicle_trip_template.xml",
        "report/vehicle_trip_passout_template.xml",
        "report/fuel_report_template.xml",
        "report/fuel_report_action.xml",
    ],
    "installable": True,
    "application": True,
}
